var a,b,c,d,e,f,g;
a=2;
a=a-1;
document.write(+a+"<br>");
a++;
b=8;
b+=2;
document.write(+b+"<br>");
c=a+b*b;
document.write(+c+"<br>");
d=a*b+b;
document.write(+d+"<br>");
e=a*(b+b);
document.write(+e+"<br>");
f=a*b/a;
document.write(+f+"<br>");
g=b/a*a;
document.write(+g+"<br>");